language: ruby
rvm:
  - 2.3.1
install:
  - bundle install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: gh_pages
  on:
    branch: master
