language: ruby
rvm:
  - 2.5
install:
  - bundle install
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  target_branch: gh-pages
  on:
    branch: master
