# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Serdar Kuzucu
email: serdar.kuzucu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://demo.serdarkuzucu.com" # the base hostname & protocol for your site
twitter_link: https://twitter.com/sedran
stackoverflow_link: http://stackoverflow.com/users/618279/sedran
linkedin_link: http://tr.linkedin.com/in/serdarkuzucu
facebook_link: https://www.facebook.com/srdrkzc
github_link: https://github.com/sedran
excerpt_separator: <!--more-->

google_search_url: http://www.google.com/search

# Build settings
markdown: kramdown

# Any plugins within jekyll_plugin group from Gemfile
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-compose
  - jekyll-redirect-from
  - jekyll-archives

# Exclude these files from the build process results.
# Prevents them from showing up in the master branch which
# is the live site.
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Rakefile

jekyll-archives:
  enabled:
    - categories
  layouts:
#    year: archive/year
#    month: archive/month
#    day: archive/day
#    tag: archive/tag
    category: category
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tags/:name/'
    category: '/category/:name/'
